name: Deploy to GoDaddy via FTP

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (ignore peer conflicts)
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Deploy via FTPS to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.butterandbytes.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: dist/
          server-dir: ${{ secrets.FTP_PATH }}
          dangerous-clean-slate: false
